export const tableData = [
  {
    id: "1",
    class: "K320B",
    student: "Dương tiến Đạt",
    debt: "89600",
    subject: "Pháp luận đại cương",
    creditNumber: 2,
    clear: "Đang chờ",
    note: "------------",
  },
  {
    id: "1",
    class: "K320B",
    student: "Dương tiến Đạt",
    debt: "89600",
    subject: "Tiếng anh cơ bản 1",
    creditNumber: 3,
    clear: "Đang chờ",
    note: "------------",
  },
  {
    id: "1",
    class: "K320B",
    student: "Dương tiến Đạt",
    debt: "89600",
    subject: "Giải tích 1",
    creditNumber: 3,
    clear: "------------",
    note: "Đã xong chờ thi",
  },
  {
    id: "1",
    class: "K320B",
    student: "Dương tiến Đạt",
    debt: "89600",
    subject: "Tin học đại cương",
    creditNumber: 3,
    clear: "Đang chờ",
    note: "------------",
  },
  {
    id: "1",
    class: "K320B",
    student: "Dương tiến Đạt",
    debt: "89600",
    subject: "Triết học Mac-lenin",
    creditNumber: 3,
    clear: "Đang chờ",
    note: "------------",
  },
  {
    id: "1",
    class: "K320B",
    student: "Dương tiến Đạt",
    debt: "89600",
    subject: "Cơ sở dữ liệu",
    creditNumber: 3,
    clear: "------------",
    note: "Đã xong chờ thi",
  },
  {
    id: "1",
    class: "K320B",
    student: "Dương tiến Đạt",
    debt: "89600",
    subject: "Mạng và truyền thông",
    creditNumber: 3,
    clear: "------------",
    note: "Đã xong chờ thi",
  },
  {
    id: "1",
    class: "K320B",
    student: "Dương tiến Đạt",
    debt: "89600",
    subject: "Tiến anh cơ bản 2",
    creditNumber: 3,
    clear: "------------",
    note: "Chưa đến thời gian học",
  },
  {
    id: "1",
    class: "K320B",
    student: "Dương tiến Đạt",
    debt: "89600",
    subject: "Giải tích 2",
    creditNumber: 0,
    clear: "------------",
    note: "Khả năng được miễn",
  },
  {
    id: "1",
    class: "K320B",
    student: "Dương tiến Đạt",
    debt: "89600",
    subject: "Lý thuyết xác xuất và thông kê toán học",
    creditNumber: 0,
    clear: "------------",
    note: "Khả năng được miễn",
  },
  {
    id: "1",
    class: "K320B",
    student: "Dương tiến Đạt",
    debt: "89600",
    subject: "Nguyên lý hệ điều hành",
    creditNumber: 3,
    clear: "------------",
    note: "Chưa đến thời gian học",
  },
  {
    id: "1",
    class: "K320B",
    student: "Dương tiến Đạt",
    debt: "89600",
    subject: "Thiết kế Web",
    creditNumber: 4,
    clear: "------------",
    note: "Chưa đến thời gian học",
  },
  {
    id: "1",
    class: "K320B",
    student: "Dương tiến Đạt",
    debt: "89600",
    subject: "Thiết kế trả nghiệm người dùng",
    creditNumber: 3,
    clear: "------------",
    note: "Chưa đến thời gian học",
  },
];
